syntax = "proto3";

package opentelemetry.proto.logs.v1;

import "opentelemetry/proto/common/v1/common.proto";
import "opentelemetry/proto/resource/v1/resource.proto";

option csharp_namespace = "OpenTelemetry.Proto.Logs.V1";
option go_package = "go.opentelemetry.io/proto/otlp/logs/v1";
option java_multiple_files = true;
option java_outer_classname = "LogsProto";
option java_package = "io.opentelemetry.proto.logs.v1";

message LogsData {
    repeated ResourceLogs resource_logs = 1;
}

message ResourceLogs {
    resource.v1.Resource resource = 1;
    repeated ScopeLogs scope_logs = 2;
    string schema_url = 3;
    
    reserved 1000;
}

message ScopeLogs {
    common.v1.InstrumentationScope scope = 1;
    repeated LogRecord log_records = 2;
    string schema_url = 3;
}

message LogRecord {
    fixed64 time_unix_nano = 1;
    fixed64 observed_time_unix_nano = 11;
    SeverityNumber severity_number = 2;
    string severity_text = 3;
    common.v1.AnyValue body = 5;
    repeated common.v1.KeyValue attributes = 6;
    uint32 dropped_attributes_count = 7;
    fixed32 flags = 8;
    bytes trace_id = 9;
    bytes span_id = 10;
    
    reserved 4;
}

enum SeverityNumber {
    SEVERITY_NUMBER_UNSPECIFIED = 0;
    SEVERITY_NUMBER_TRACE = 1;
    SEVERITY_NUMBER_TRACE2 = 2;
    SEVERITY_NUMBER_TRACE3 = 3;
    SEVERITY_NUMBER_TRACE4 = 4;
    SEVERITY_NUMBER_DEBUG = 5;
    SEVERITY_NUMBER_DEBUG2 = 6;
    SEVERITY_NUMBER_DEBUG3 = 7;
    SEVERITY_NUMBER_DEBUG4 = 8;
    SEVERITY_NUMBER_INFO = 9;
    SEVERITY_NUMBER_INFO2 = 10;
    SEVERITY_NUMBER_INFO3 = 11;
    SEVERITY_NUMBER_INFO4 = 12;
    SEVERITY_NUMBER_WARN = 13;
    SEVERITY_NUMBER_WARN2 = 14;
    SEVERITY_NUMBER_WARN3 = 15;
    SEVERITY_NUMBER_WARN4 = 16;
    SEVERITY_NUMBER_ERROR = 17;
    SEVERITY_NUMBER_ERROR2 = 18;
    SEVERITY_NUMBER_ERROR3 = 19;
    SEVERITY_NUMBER_ERROR4 = 20;
    SEVERITY_NUMBER_FATAL = 21;
    SEVERITY_NUMBER_FATAL2 = 22;
    SEVERITY_NUMBER_FATAL3 = 23;
    SEVERITY_NUMBER_FATAL4 = 24;
}

enum LogRecordFlags {
    LOG_RECORD_FLAGS_DO_NOT_USE = 0;
    LOG_RECORD_FLAGS_TRACE_FLAGS_MASK = 255;
}
